var lang = {
    Create  : "Hinzufügen",
    Cancel  : "Stornieren",
    Update  : "Aktualisieren",
    Delete  : "Löschen",
    Unit    : "Einheit",
    Date    : "Datum der Applikation",
    Product : "Produkt",
    RegNum  : "Pfl. Reg. Nr.",
    PerVineyard             : "Produkt pro Weingartenfläche  (kg, l)",
    AutocompletePlaceholder : "Beginne zu tippen ...",
    FarmPlaceholder         : "Weingartenfläche auswählen",
    EquipmentPlaceholder    : "Pflanzenschutzgerät auswählen",
    DoseRatePercent         : "Aufwandmenge für 10.000 m2",
    AltArea                 : "Behandelte Fläche [ha]",
    OpenedNozzles           : "Geöffnete (benützte) Düsen",
    SavedWater              : "Einsparung bei Recyclinggeräten [%]",
    Savings                 : "Speichern",
    WaterVolume             : "Spritzbrühe [L / ha]",
    PerDevice               : "Produktmenge pro Pflanzenschutzgerät [kg, L, Stk]",
    PerHA                   : "Berechnete Aufwandmenge pro ha [kg, L, Stk]",
    RowsDistance            : "Reihenabstand [m]",
    DoseRateKM              : "Aufwandmenge pro ha",
    MaxDoseRate             : "Max. AWM pro ha Grundfläche [kg,l]",
    LeafWallHeight          : "Höhe der Laubwand [m]",
    FarmMissingTitle        : " Wähle einen Weinberg!",
    FarmMissingText         : "Wähle einen Weingarten aus um fortzufahren",
    EquipmentMissingTitle   : "wählen einen PFLANZENSCHUTZGERÄT HINZU",
    EquipmentMissingText    : "Um mit der Berechnung fortzufahren, wählen Sie bitte eine Spritze aus.",
    CalcualtionMethod       : "Berechnungsmethode",
    GrowthStage             : "Reb-Entwicklungsstadium",
    Vineyard                : "Weingartenfläche",
    SprayingDevice          : "Pflanzenschutzgerät",
    VineyardSize            : "Größe der Weingartenfläche [ha]",
    DeviceVolume            : "Inhalt des Pflanzenschutzgeräts [l]",
    Water100LWA             : "Wassermenge bei voller (100%) Laubwandentwicklung [l]",
    Nozzles100LWA           : "Anzahl der offenen Düsen bei voller Belaubung [Stk]",
    EquipmentId             : "Pflanzenschutzgerät ID",
    EquipmentName           : "Equipment name",
    TreatmentAdd            : "Füge ein neues Produkt hinzu",
    addProductToSpraying    : "Füge ein neues Produkt hinzu",
    CalculationRemove       : "Berechnungstabelle entfernen",
    CalculationRemoveText   : "Sie versuchen eine Kalkulation zu entfernen.<br>Wähle <strong>Löschen</strong> um Sprühplan zu entfernen oder <strong>Stornieren</strong> um dieses Fenster zu schließen.",
    RemoveBtn               : "Löschen",
    Warning                 : "Warnung!",
    TableExists             : "Kalkulation für dieses Wachstumsstadium existiert bereits.",
    ButtonOK                : "Ok",
    austrieb                : "Austrieb",
    erste_vorblute          : "Erste Vorblüte",
    classic                 : "Klassische Kalkulation",
    leaf_wall               : "LWA kalkulation",
    Error                   : "Error",
    LwaError                : "Vorsicht – Die maximale ha-Aufwandmenge wird überschritten!",
    SaveSprayingPlan        : "Spritzung speichern",
    SaveSprayingPlanTitle   : "Sprühplan wurde gespeichert",
    SaveSprayingPlanText    : "Sprühplan wurde Erfolg gerettet!",
    UpdateSprayingPlan      : "Spritzung ändern",
    UpdateSprayingPlanTitle : "Sprühplan wurde aktualisiert",
    UpdateSprayingPlanText  : "Sprühplan wurde erfolgreich aktualisiert!",
    DeleteSprayingPlan      : "Sprühplan löschen",
    DeleteSprayingPlanTitle : "Die Spritzung wurde gelöscht.",
    DeleteSprayingPlanText  : "Die Spritzung wurde gelöscht.",
    EmptySprayingPlan       : "Die Spritzung ist leer",
    EmptySprayingPlanText   : "Add product items to Spraying plan.",
    SprayingDate            : "Spritzdatum",
    FarmMissingSprayingDate : "Spritzdatum auswählen!",
    FarmMissingSprayingDateText    : "Wähle ein Datum für deine Spritzung"
};
