var lang = {
    Create                          : "Create",
    Update                          : "Update",
    Delete                          : "Delete",
    Unit                            : "Unit",
    Date                            : "Date of spraying",
    Product                         : "Product",
    RegNum                          : "Reg. number",
    PerVineyard                     : "Product per vineyard (kg/l)",
    AutocompletePlaceholder         : "Start typing ..",
    FarmPlaceholder                 : "Select farm",
    EquipmentPlaceholder            : "Select equipment",
    DoseRatePercent                 : 'Dose rate for 100 % leaf wall area',
    AltArea                         : 'Alternative treated area (ha)',
    OpenedNozzles                   : 'Opened (used) nozzles',
    SavedWater                      : 'Saved water (%)',
    WaterVolume                     : 'Water volume (l/ha)',
    PerDevice                       : 'Product per spraying device(kg/l)',
    PerHA                           : 'Does rate pre ha (kg/l)',
    RowsDistance                    : 'Distance between rows [m]',
    DoseRateKM                      : 'Dose rate for 10 km leaf wall area',
    MaxDoseRate                     : 'Max dose rate per ha',
    LeafWallHeight                  : 'Height of leaf wall',
    FarmMissingTitle                : 'Choose a farm!',
    FarmMissingText                 : 'To continue with your calculations, choose a farm.',
    FarmMissingSprayingDate         : 'Select the spray date!',
    FarmMissingSprayingDateText     : 'To continue with your calculations select the spray date.',
    EquipmentMissingTitle           : 'Choose a equipment!',
    EquipmentMissingText            : 'To continue with your calculations, choose a equipment.',
    CalcualtionMethod               : 'Calculation method',
    GrowthStage                     : 'Growth stage',
    Vineyard                        : 'Vineyard',
    SprayingDevice                  : 'Spraying device',
    VineyardSize                    : 'Size of the vineyard [ha]',
    DeviceVolume                    : 'Volume of the spraying device [L]',
    Water100LWA                     : 'Used water volume for 100 % leaf wall area [L]',
    Nozzles100LWA                   : 'Amount of used nozzles for 100 % leaf wall area [pcs]',
    EquipmentId                     : 'Equipment ID',

    TreatmentAdd                    : 'Add a new treatment',
    CalculationRemove               : 'Remove calculation',
    CalculationRemoveText           : 'You are about to remove a calculation table.<br> Click <strong>Remove</strong> button to remove calculation or <strong>Cancel</strong> button dismiss this window.',
    RemoveBtn                       : 'Remove',

    Warning                         : 'Warning!',
    TableExists                     : 'Calculation table for selected growth stage already exists.',

    ButtonOK                        : 'Ok',

    austrieb                        : "Austrieb",
    erste_vorblute                  : "Erste Vorblüte",

    classic                         : "Klassische Kalkulation",
    leaf_wall                       : "LWA-Kalkulation",

};
